---
- name: Create 10 nginx containers for load balancing
  hosts: all
  tasks:
   - name: Create 10 nginx containers
     docker_container:
      image: nginx
      name: "container{{item}}"
     with_sequence: count=10
