---
- name: Install s.w applications
  hosts: all
  tasks:
   - name: Install s/w
     apt:
      name: "{{item.a}}"
      state: "{{item.b}}"
      update_cache: "{{item.c}}"
     with_items:
      - {a: tree,b: present,c: no}
      - {a: openjdk-8-jdk,b: absent,c: no}
      - {a: maven,b: latest,c: yes}

...
